### PR TITLE
Update mt_pe.h

### PR DESCRIPTION
**Pull request by pro4tlzz**
Added 1.67a charging for 5v. just a test to see if 5v is functioning correctly.

### CODE REVIEW

**Comment by leskal** [comment]
i build kernel with you changes an i will send you flashable zip to install it

**Comment by pro4tlzz** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Nov 28, 2016 at 4:51 PM +0000, "Alex Kalles" <notifications@github.com<mailto:notifications@github.com>> wrote:


i build kernel with you changes an i will send you flashable zip to install it

**Comment by leskal** [comment]
[3.18.44-KERNEL-TEST.zip](https://github.com/JonnyXDA/android_kernel_elephone_p9000/files/616956/3.18.44-KERNEL-TEST.zip)

**Comment by pro4tlzz** [comment]
Just tested it. Phone does not go above 5v
I really hope elephone release kernel for s7 since that also used pump express and the same charger as the p9000

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Nov 28, 2016 at 5:18 PM +0000, "Alex Kalles" <notifications@github.com<mailto:notifications@github.com>> wrote:


3.18.44-KERNEL-TEST.zip<https://github.com/JonnyXDA/android_kernel_elephone_p9000/files/616956/3.18.44-KERNEL-TEST.zip>

**Comment by leskal** [comment]
so not merge because it doesn't change anything, ok?

**Comment by pro4tlzz** [comment]
do not merge it. doesn't fix anything


________________________________

**Pull request closed without merging**
